apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant1-app-of-apps
  namespace: tenant1
spec:
  destination:
    namespace: tenant1
    server: https://kubernetes.default.svc
  project: tenant1-project
  source:
    path: argo-apps/tenant1/parent
    repoURL: https://github.com/agiertli/instance-scoped-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true