apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant2-project
  namespace: tenant2
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: ArgoCD Project for Tooling
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
